DECLARE @CANCELLATIONDATE DATETIME ='2019-05-18 17:16:34.187'

SELECT @CANCELLATIONDATE

SELECT CASE WHEN @CANCELLATIONDATE =GETDATE() THEN '100%'
			 WHEN @CANCELLATIONDATE BETWEEN DATEADD(WEEK,-2,GETDATE()) AND DATEADD(WEEK,-1,GETDATE()) THEN '75%'
			 
			 WHEN @CANCELLATIONDATE <=DATEADD(MONTH,1,GETDATE()) THEN '50%'
			 
			 END
			 ,DATEADD(WEEK,-2,GETDATE())
			 ,DATEADD(WEEK,-1,GETDATE())
